/PhysicalProperty
/PhysicalProperty/Property[]
/PhysicalProperty/Property[]/Identification
/PhysicalProperty/Property[]/Identification/IDValue
/PhysicalProperty/Property[]/PropertyID
/PhysicalProperty/Property[]/PropertyID/Identification[]
/PhysicalProperty/Property[]/PropertyID/Identification[]/IDValue
/PhysicalProperty/Property[]/PropertyID/MarketingName
/PhysicalProperty/Property[]/PropertyID/WebSite
/PhysicalProperty/Property[]/PropertyID/Address
/PhysicalProperty/Property[]/PropertyID/Address/Address
/PhysicalProperty/Property[]/PropertyID/Address/City
/PhysicalProperty/Property[]/PropertyID/Address/State
/PhysicalProperty/Property[]/PropertyID/Address/PostalCode
/PhysicalProperty/Property[]/PropertyID/Address/Email
/PhysicalProperty/Property[]/PropertyID/Phone
/PhysicalProperty/Property[]/PropertyID/Phone/PhoneNumber
/PhysicalProperty/Property[]/ILS_Identification
/PhysicalProperty/Property[]/ILS_Identification/Latitude
/PhysicalProperty/Property[]/ILS_Identification/Longitude
/PhysicalProperty/Property[]/Information
/PhysicalProperty/Property[]/Information/StructureType
/PhysicalProperty/Property[]/Information/UnitCount
/PhysicalProperty/Property[]/Information/OfficeHour[]
/PhysicalProperty/Property[]/Information/OfficeHour[]/OpenTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/CloseTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/Day
/PhysicalProperty/Property[]/Information/ShortDescription
/PhysicalProperty/Property[]/Information/LongDescription
/PhysicalProperty/Property[]/Information/Rents
/PhysicalProperty/Property[]/Information/Rents/SalePrice
/PhysicalProperty/Property[]/Information/Rents/StartRent
/PhysicalProperty/Property[]/Information/Rents/StandardRent
/PhysicalProperty/Property[]/Information/Rents/CorporateRent
/PhysicalProperty/Property[]/Information/DrivingDirections
/PhysicalProperty/Property[]/Information/PropertyAvailabilityURL
/PhysicalProperty/Property[]/Floorplan[]
/PhysicalProperty/Property[]/Floorplan[]/Identification
/PhysicalProperty/Property[]/Floorplan[]/Identification/IDValue
/PhysicalProperty/Property[]/Floorplan[]/FloorplanType
/PhysicalProperty/Property[]/Floorplan[]/Name
/PhysicalProperty/Property[]/Floorplan[]/UnitCount
/PhysicalProperty/Property[]/Floorplan[]/FloorplanAvailabilityURL
/PhysicalProperty/Property[]/Floorplan[]/UnitsAvailable
/PhysicalProperty/Property[]/Floorplan[]/Room[]
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Count
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Comment
/PhysicalProperty/Property[]/Floorplan[]/SquareFeet
/PhysicalProperty/Property[]/Floorplan[]/MarketRent
/PhysicalProperty/Property[]/Floorplan[]/EffectiveRent
/PhysicalProperty/Property[]/Floorplan[]/LeaseTerm
/PhysicalProperty/Property[]/Floorplan[]/Deposit
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Amount
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Amount/ValueRange
/PhysicalProperty/Property[]/Floorplan[]/File[]
/PhysicalProperty/Property[]/Floorplan[]/File[]/FileType
/PhysicalProperty/Property[]/Floorplan[]/File[]/Description
/PhysicalProperty/Property[]/Floorplan[]/File[]/Name
/PhysicalProperty/Property[]/Floorplan[]/File[]/Format
/PhysicalProperty/Property[]/Floorplan[]/File[]/Src
/PhysicalProperty/Property[]/Floorplan[]/File[]/Width
/PhysicalProperty/Property[]/Floorplan[]/File[]/Height
/PhysicalProperty/Property[]/Floorplan[]/File[]/Rank
/PhysicalProperty/Property[]/Floorplan[]/Promotional
/PhysicalProperty/Property[]/File[]
/PhysicalProperty/Property[]/File[]/FileType
/PhysicalProperty/Property[]/File[]/Name
/PhysicalProperty/Property[]/File[]/Format
/PhysicalProperty/Property[]/File[]/Src
/PhysicalProperty/Property[]/File[]/Width
/PhysicalProperty/Property[]/File[]/Height
/PhysicalProperty/Property[]/File[]/Rank
/PhysicalProperty/Property[]/Promotional
/PhysicalProperty/Property[]/Floorplan[]/File
/PhysicalProperty/Property[]/Floorplan[]/File/FileType
/PhysicalProperty/Property[]/Floorplan[]/File/Description
/PhysicalProperty/Property[]/Floorplan[]/File/Name
/PhysicalProperty/Property[]/Floorplan[]/File/Format
/PhysicalProperty/Property[]/Floorplan[]/File/Src
/PhysicalProperty/Property[]/Floorplan[]/File/Width
/PhysicalProperty/Property[]/Floorplan[]/File/Height
/PhysicalProperty/Property[]/Floorplan[]/File/Rank