/PhysicalProperty
/PhysicalProperty/Management[]
/PhysicalProperty/Management[]/Name
/PhysicalProperty/Property[]
/PhysicalProperty/Property[]/Identification
/PhysicalProperty/Property[]/Identification/PrimaryID
/PhysicalProperty/Property[]/Identification/SecondaryID
/PhysicalProperty/Property[]/Identification/General_ID
/PhysicalProperty/Property[]/Identification/General_ID/ID
/PhysicalProperty/Property[]/Identification/General_ID/Description
/PhysicalProperty/Property[]/Identification/OwnerLegalName
/PhysicalProperty/Property[]/Floorplan[]
/PhysicalProperty/Property[]/Floorplan[]/Name
/PhysicalProperty/Property[]/Floorplan[]/Room[]
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Count
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Comment
/PhysicalProperty/Property[]/Floorplan[]/SquareFeet
/PhysicalProperty/Property[]/Floorplan[]/MarketRent
/PhysicalProperty/Property[]/Floorplan[]/EffectiveRent
/PhysicalProperty/Property[]/Floorplan[]/Deposit
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Amount
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Description
/PhysicalProperty/Property[]/Floorplan[]/Amenities
/PhysicalProperty/Property[]/Floorplan[]/Amenities/General
/PhysicalProperty/Property[]/Floorplan
/PhysicalProperty/Property[]/Floorplan/Name
/PhysicalProperty/Property[]/Floorplan/Room[]
/PhysicalProperty/Property[]/Floorplan/Room[]/Count
/PhysicalProperty/Property[]/Floorplan/Room[]/Comment
/PhysicalProperty/Property[]/Floorplan/SquareFeet
/PhysicalProperty/Property[]/Floorplan/MarketRent
/PhysicalProperty/Property[]/Floorplan/EffectiveRent
/PhysicalProperty/Property[]/Floorplan/Amenities
/PhysicalProperty/Property[]/Floorplan/Amenities/General