/PhysicalProperty
/PhysicalProperty/Property[]
/PhysicalProperty/Property[]/PropertyID
/PhysicalProperty/Property[]/PropertyID/Identification
/PhysicalProperty/Property[]/PropertyID/Identification/PrimaryID
/PhysicalProperty/Property[]/PropertyID/Identification/MarketingName
/PhysicalProperty/Property[]/PropertyID/Identification/WebSite
/PhysicalProperty/Property[]/PropertyID/Identification/BozzutoURL
/PhysicalProperty/Property[]/PropertyID/Identification/Latitude
/PhysicalProperty/Property[]/PropertyID/Identification/Longitude
/PhysicalProperty/Property[]/PropertyID/Address
/PhysicalProperty/Property[]/PropertyID/Address/Address1
/PhysicalProperty/Property[]/PropertyID/Address/City
/PhysicalProperty/Property[]/PropertyID/Address/State
/PhysicalProperty/Property[]/PropertyID/Address/PostalCode
/PhysicalProperty/Property[]/PropertyID/Address/CountyName
/PhysicalProperty/Property[]/PropertyID/Address/Lead2LeaseEmail
/PhysicalProperty/Property[]/PropertyID/Phone
/PhysicalProperty/Property[]/PropertyID/Phone/PhoneNumber
/PhysicalProperty/Property[]/Information
/PhysicalProperty/Property[]/Information/OfficeHour[]
/PhysicalProperty/Property[]/Information/OfficeHour[]/OpenTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/CloseTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/Day
/PhysicalProperty/Property[]/Information/OverviewText
/PhysicalProperty/Property[]/Information/OverviewTextStripped
/PhysicalProperty/Property[]/Information/OverviewBullet1
/PhysicalProperty/Property[]/Information/OverviewBullet2
/PhysicalProperty/Property[]/Information/OverviewBullet3
/PhysicalProperty/Property[]/Information/NeighborhoodText
/PhysicalProperty/Property[]/Information/DirectionsURL
/PhysicalProperty/Property[]/Information/ListingImageURL
/PhysicalProperty/Property[]/Information/VideoURL
/PhysicalProperty/Property[]/Information/FacebookURL
/PhysicalProperty/Property[]/Information/TwitterHandle
/PhysicalProperty/Property[]/Information/PinterestURL
/PhysicalProperty/Property[]/Feature[]
/PhysicalProperty/Property[]/Feature[]/Title
/PhysicalProperty/Property[]/Feature[]/Description
/PhysicalProperty/Property[]/FeaturedButton[]
/PhysicalProperty/Property[]/FeaturedButton[]/Name
/PhysicalProperty/Property[]/PhotoSet
/PhysicalProperty/Property[]/Slideshow
/PhysicalProperty/Property[]/Slideshow/SlideshowImageURL[]
/PhysicalProperty/Property[]/Floorplan[]
/PhysicalProperty/Property[]/Floorplan[]/Name
/PhysicalProperty/Property[]/Floorplan[]/FloorplanAvailabilityURL
/PhysicalProperty/Property[]/Floorplan[]/DisplayedUnitsAvailable
/PhysicalProperty/Property[]/Floorplan[]/ImageURL
/PhysicalProperty/Property[]/Floorplan[]/Bedrooms
/PhysicalProperty/Property[]/Floorplan[]/Bathrooms
/PhysicalProperty/Property[]/Floorplan[]/SquareFeet
/PhysicalProperty/Property[]/Floorplan[]/MarketRent
/PhysicalProperty/Property[]/Floorplan[]/EffectiveRent
/PhysicalProperty/Property[]/Promotion
/PhysicalProperty/Property[]/NearbyCommunity[]
/PhysicalProperty/Property[]/NearbyCommunity[]/Name