/PhysicalProperty
/PhysicalProperty/Management[]
/PhysicalProperty/Management[]/Name
/PhysicalProperty/Management[]/Address
/PhysicalProperty/Management[]/Address/Address1
/PhysicalProperty/Management[]/Address/City
/PhysicalProperty/Management[]/Address/State
/PhysicalProperty/Management[]/Address/Zip
/PhysicalProperty/Management[]/Email
/PhysicalProperty/Management[]/WebSite
/PhysicalProperty/Property[]
/PhysicalProperty/Property[]/Identification
/PhysicalProperty/Property[]/Identification/PrimaryID
/PhysicalProperty/Property[]/Identification/SecondaryID
/PhysicalProperty/Property[]/Identification/General_ID
/PhysicalProperty/Property[]/Identification/General_ID/ID
/PhysicalProperty/Property[]/Identification/General_ID/Description
/PhysicalProperty/Property[]/Identification/MarketingName
/PhysicalProperty/Property[]/Identification/OwnerLegalName
/PhysicalProperty/Property[]/Identification/Address
/PhysicalProperty/Property[]/Identification/Address/Address1
/PhysicalProperty/Property[]/Identification/Address/City
/PhysicalProperty/Property[]/Identification/Address/State
/PhysicalProperty/Property[]/Identification/Address/Zip
/PhysicalProperty/Property[]/Identification/Address/Country
/PhysicalProperty/Property[]/Identification/Address/PO_Box
/PhysicalProperty/Property[]/Identification/Address/MailingAddress
/PhysicalProperty/Property[]/Identification/Address/ShippingAddress
/PhysicalProperty/Property[]/Identification/Latitude
/PhysicalProperty/Property[]/Identification/Longitude
/PhysicalProperty/Property[]/Identification/DaylightSaving
/PhysicalProperty/Property[]/Identification/WebSite
/PhysicalProperty/Property[]/Identification/Phone
/PhysicalProperty/Property[]/Identification/Phone/Number
/PhysicalProperty/Property[]/Identification/Phone/Extension
/PhysicalProperty/Property[]/Identification/Email
/PhysicalProperty/Property[]/Information
/PhysicalProperty/Property[]/Information/StructureType
/PhysicalProperty/Property[]/Information/BuildingCount
/PhysicalProperty/Property[]/Information/UnitCount
/PhysicalProperty/Property[]/Information/NumberOfAcres
/PhysicalProperty/Property[]/Information/YearBuilt
/PhysicalProperty/Property[]/Information/YearRemodeled
/PhysicalProperty/Property[]/Information/AcquisitionDate
/PhysicalProperty/Property[]/Information/OfficeHour[]
/PhysicalProperty/Property[]/Information/OfficeHour[]/OpenTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/CloseTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/Day
/PhysicalProperty/Property[]/Information/ShortDescription
/PhysicalProperty/Property[]/Information/LongDescription
/PhysicalProperty/Property[]/Information/DrivingDirections
/PhysicalProperty/Property[]/Information/LeaseLength
/PhysicalProperty/Property[]/Information/Parking[]
/PhysicalProperty/Property[]/Information/Parking[]/Assigned
/PhysicalProperty/Property[]/Information/Parking[]/AssignedFee
/PhysicalProperty/Property[]/Information/Parking[]/Spaces
/PhysicalProperty/Property[]/Information/Parking[]/Comment
/PhysicalProperty/Property[]/Information/Services
/PhysicalProperty/Property[]/Information/Services/Name
/PhysicalProperty/Property[]/Information/Services/Detail
/PhysicalProperty/Property[]/Information/Services/DistanceTo
/PhysicalProperty/Property[]/Information/Services/Comment
/PhysicalProperty/Property[]/Policy
/PhysicalProperty/Property[]/Policy/Pet[]
/PhysicalProperty/Property[]/Policy/Pet[]/Comment
/PhysicalProperty/Property[]/Policy/Pet[]/MaxCount
/PhysicalProperty/Property[]/Policy/Pet[]/Deposit
/PhysicalProperty/Property[]/Policy/Pet[]/Fee
/PhysicalProperty/Property[]/Policy/Pet[]/Rent
/PhysicalProperty/Property[]/Policy/Pet[]/Weight
/PhysicalProperty/Property[]/Policy/Pet[]/FeeRange
/PhysicalProperty/Property[]/Policy/Pet[]/Restrictions
/PhysicalProperty/Property[]/Policy/Pet[]/PetCare
/PhysicalProperty/Property[]/Floorplan[]
/PhysicalProperty/Property[]/Floorplan[]/Name
/PhysicalProperty/Property[]/Floorplan[]/UnitCount
/PhysicalProperty/Property[]/Floorplan[]/UnitsAvailable
/PhysicalProperty/Property[]/Floorplan[]/DisplayedUnitsAvailable
/PhysicalProperty/Property[]/Floorplan[]/TotalRoomCount
/PhysicalProperty/Property[]/Floorplan[]/Room[]
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Count
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Comment
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Size
/PhysicalProperty/Property[]/Floorplan[]/SquareFeet
/PhysicalProperty/Property[]/Floorplan[]/MarketRent
/PhysicalProperty/Property[]/Floorplan[]/EffectiveRent
/PhysicalProperty/Property[]/Floorplan[]/Deposit
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Amount
/PhysicalProperty/Property[]/Floorplan[]/Deposit/PercentRefundable
/PhysicalProperty/Property[]/Floorplan[]/Deposit/PortionRefundable
/PhysicalProperty/Property[]/Floorplan[]/Amenities
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Alarm
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Balcony
/PhysicalProperty/Property[]/Floorplan[]/Amenities/CableSat
/PhysicalProperty/Property[]/Floorplan[]/Amenities/DishWasher
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Disposal
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Garage
/PhysicalProperty/Property[]/Floorplan[]/Amenities/View
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Washer
/PhysicalProperty/Property[]/Floorplan[]/Amenities/WheelChair
/PhysicalProperty/Property[]/Floorplan[]/Amenities/WD_Hookup
/PhysicalProperty/Property[]/Floorplan[]/Amenities/WindowCoverings
/PhysicalProperty/Property[]/Floorplan[]/AirCon
/PhysicalProperty/Property[]/Floorplan[]/AirCon/Type
/PhysicalProperty/Property[]/Floorplan[]/AirCon/Description
/PhysicalProperty/Property[]/Floorplan[]/Fireplace
/PhysicalProperty/Property[]/Floorplan[]/Fireplace/Type
/PhysicalProperty/Property[]/Floorplan[]/Fireplace/Description
/PhysicalProperty/Property[]/Floorplan[]/Heat
/PhysicalProperty/Property[]/Floorplan[]/Heat/Type
/PhysicalProperty/Property[]/Floorplan[]/Heat/Description
/PhysicalProperty/Property[]/Floorplan[]/Range
/PhysicalProperty/Property[]/Floorplan[]/Range/Type
/PhysicalProperty/Property[]/Floorplan[]/Range/Description
/PhysicalProperty/Property[]/Floorplan[]/Amenities/AdditionalStorage
/PhysicalProperty/Property[]/Floorplan[]/Amenities/AirConditioner
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Carport
/PhysicalProperty/Property[]/Floorplan[]/Amenities/CeilingFan
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Courtyard
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Fireplace
/PhysicalProperty/Property[]/Floorplan[]/Amenities/LargeClosets
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Microwave
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Patio
/PhysicalProperty/Property[]/Floorplan[]/Amenities/PrivateBalcony
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Refrigerator
/PhysicalProperty/Property[]/Amenities
/PhysicalProperty/Property[]/Amenities/Community
/PhysicalProperty/Property[]/Amenities/Community/Availability24Hours
/PhysicalProperty/Property[]/Amenities/Community/BasketballCourt
/PhysicalProperty/Property[]/Amenities/Community/BusinessCenter
/PhysicalProperty/Property[]/Amenities/Community/ClubHouse
/PhysicalProperty/Property[]/Amenities/Community/Concierge
/PhysicalProperty/Property[]/Amenities/Community/CoverPark
/PhysicalProperty/Property[]/Amenities/Community/FitnessCenter
/PhysicalProperty/Property[]/Amenities/Community/FreeWeights
/PhysicalProperty/Property[]/Amenities/Community/Garage
/PhysicalProperty/Property[]/Amenities/Community/GroupExcercise
/PhysicalProperty/Property[]/Amenities/Community/HighSpeed
/PhysicalProperty/Property[]/Amenities/Community/Library
/PhysicalProperty/Property[]/Amenities/Community/OnSiteMaintenance
/PhysicalProperty/Property[]/Amenities/Community/OnSiteManagement
/PhysicalProperty/Property[]/Amenities/Community/PacakageReceiving
/PhysicalProperty/Property[]/Amenities/Community/Pool
/PhysicalProperty/Property[]/Amenities/Community/PlayGround
/PhysicalProperty/Property[]/Amenities/Community/Racquetball
/PhysicalProperty/Property[]/Amenities/Community/Sauna
/PhysicalProperty/Property[]/Amenities/Community/ShortTermLease
/PhysicalProperty/Property[]/Amenities/Community/Spa
/PhysicalProperty/Property[]/Amenities/Community/StorageSpace
/PhysicalProperty/Property[]/Amenities/Community/Sundeck
/PhysicalProperty/Property[]/Amenities/Community/TennisCourt
/PhysicalProperty/Property[]/Amenities/Community/Transportation
/PhysicalProperty/Property[]/Amenities/Community/Vintage
/PhysicalProperty/Property[]/Amenities/Community/VolleyballCourt
/PhysicalProperty/Property[]/Amenities/Floorplan
/PhysicalProperty/Property[]/Amenities/Floorplan/AdditionalStorage
/PhysicalProperty/Property[]/Amenities/Floorplan/AirConditioner
/PhysicalProperty/Property[]/Amenities/Floorplan/Balcony
/PhysicalProperty/Property[]/Amenities/Floorplan/CableSat
/PhysicalProperty/Property[]/Amenities/Floorplan/Carport
/PhysicalProperty/Property[]/Amenities/Floorplan/CeilingFan
/PhysicalProperty/Property[]/Amenities/Floorplan/Courtyard
/PhysicalProperty/Property[]/Amenities/Floorplan/DishWasher
/PhysicalProperty/Property[]/Amenities/Floorplan/Disposal
/PhysicalProperty/Property[]/Amenities/Floorplan/Fireplace
/PhysicalProperty/Property[]/Amenities/Floorplan/LargeClosets
/PhysicalProperty/Property[]/Amenities/Floorplan/Microwave
/PhysicalProperty/Property[]/Amenities/Floorplan/Patio
/PhysicalProperty/Property[]/Amenities/Floorplan/PrivateBalcony
/PhysicalProperty/Property[]/Amenities/Floorplan/Refrigerator
/PhysicalProperty/Property[]/Amenities/Floorplan/View
/PhysicalProperty/Property[]/Amenities/Floorplan/WD_Hookup
/PhysicalProperty/Property[]/Utility
/PhysicalProperty/Property[]/Utility/AirCon
/PhysicalProperty/Property[]/Utility/BroadbandInternet
/PhysicalProperty/Property[]/Utility/Cable
/PhysicalProperty/Property[]/Utility/Electric
/PhysicalProperty/Property[]/Utility/Gas
/PhysicalProperty/Property[]/Utility/Heat
/PhysicalProperty/Property[]/Utility/HotWater
/PhysicalProperty/Property[]/Utility/Sewer
/PhysicalProperty/Property[]/Utility/Telephone
/PhysicalProperty/Property[]/Utility/Trash
/PhysicalProperty/Property[]/Utility/Water
/PhysicalProperty/Property[]/Utility/UtilityPortionIncluded
/PhysicalProperty/Property[]/File[]
/PhysicalProperty/Property[]/File[]/Type
/PhysicalProperty/Property[]/File[]/Name
/PhysicalProperty/Property[]/File[]/Caption
/PhysicalProperty/Property[]/File[]/Format
/PhysicalProperty/Property[]/File[]/Src
/PhysicalProperty/Property[]/File[]/Width
/PhysicalProperty/Property[]/File[]/Height
/PhysicalProperty/Property[]/File[]/Rank
/PhysicalProperty/Property[]/File[]/AffiliateID
/PhysicalProperty/Property[]/Information/Parking
/PhysicalProperty/Property[]/Information/Parking/Assigned
/PhysicalProperty/Property[]/Information/Parking/AssignedFee
/PhysicalProperty/Property[]/Information/Parking/SpaceFee
/PhysicalProperty/Property[]/Information/Parking/Spaces
/PhysicalProperty/Property[]/Information/Parking/Comment
/PhysicalProperty/Property[]/Floorplan[]/Room
/PhysicalProperty/Property[]/Floorplan[]/Room/Count
/PhysicalProperty/Property[]/Floorplan[]/Room/Comment
/PhysicalProperty/Property[]/Floorplan[]/Room/Size
/PhysicalProperty/Property[]/Amenities/Community/Gate
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Dryer
/PhysicalProperty/Property[]/Amenities/Community/Elevator
/PhysicalProperty/Property[]/Policy/Pet
/PhysicalProperty/Property[]/Policy/Pet/Comment
/PhysicalProperty/Property[]/Policy/Pet/MaxCount
/PhysicalProperty/Property[]/Policy/Pet/Deposit
/PhysicalProperty/Property[]/Policy/Pet/Fee
/PhysicalProperty/Property[]/Policy/Pet/Rent
/PhysicalProperty/Property[]/Policy/Pet/Weight
/PhysicalProperty/Property[]/Policy/Pet/FeeRange
/PhysicalProperty/Property[]/Policy/Pet/Restrictions
/PhysicalProperty/Property[]/Policy/Pet/PetCare
/PhysicalProperty/Property[]/Floorplan[]/Amenities/IndividualClimateControl
/PhysicalProperty/Property[]/Amenities/Community/Laundry
/PhysicalProperty/Property[]/Amenities/Community/RecRoom
/PhysicalProperty/Property[]/Amenities/Floorplan/Dryer
/PhysicalProperty/Property[]/Amenities/Floorplan/IndividualClimateControl
/PhysicalProperty/Property[]/Amenities/Floorplan/Washer
/PhysicalProperty/Property[]/Amenities/Floorplan/WindowCoverings
/PhysicalProperty/Property[]/Amenities/Community/DoorAttendant
/PhysicalProperty/Property[]/Amenities/Community/NightPatrol
/PhysicalProperty/Property[]/Floorplan[]/Amenities/PrivatePatio
/PhysicalProperty/Property[]/Amenities/Floorplan/Garage
/PhysicalProperty/Property[]/Amenities/Floorplan/PrivatePatio
/PhysicalProperty/Property[]/Identification/Fax
/PhysicalProperty/Property[]/Identification/Fax/Number
/PhysicalProperty/Property[]/Identification/Fax/Extension
/PhysicalProperty/Property[]/Information/Services[]
/PhysicalProperty/Property[]/Information/Services[]/Name
/PhysicalProperty/Property[]/Information/Services[]/Detail
/PhysicalProperty/Property[]/Amenities/Community/TVLounge
/PhysicalProperty/Property[]/Floorplan[]/Amenities/ControlledAccess
/PhysicalProperty/Property[]/Amenities/Floorplan/ControlledAccess
/PhysicalProperty/Property[]/Amenities/Community/GuestRoom
/PhysicalProperty/Property[]/Identification/Phone[]
/PhysicalProperty/Property[]/Identification/Phone[]/Number
/PhysicalProperty/Property[]/Identification/Phone[]/Extension
/PhysicalProperty/Property[]/Concession
/PhysicalProperty/Property[]/Concession/Value
/PhysicalProperty/Property[]/Concession/Term
/PhysicalProperty/Property[]/Concession/Description
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Furnished
/PhysicalProperty/Property[]/Amenities/Floorplan/Alarm
/PhysicalProperty/Property[]/Amenities/Floorplan/Furnished
/PhysicalProperty/Property[]/Floorplan[]/Amenities/General
/PhysicalProperty/Property[]/Identification/MSA_Number
/PhysicalProperty/Property[]/Information/Services[]/DistanceTo
/PhysicalProperty/Property[]/Information/Services[]/Comment
/PhysicalProperty/Property[]/Amenities/Community/HouseSitting
/PhysicalProperty/Property[]/Amenities/Community/Housekeeping
/PhysicalProperty/Property[]/Amenities/Floorplan/WheelChair
/PhysicalProperty/Property[]/Floorplan[]/Concession
/PhysicalProperty/Property[]/Floorplan[]/Concession/Value
/PhysicalProperty/Property[]/Floorplan[]/Concession/Term
/PhysicalProperty/Property[]/Floorplan[]/Concession/Description
/PhysicalProperty/Property[]/Fee
/PhysicalProperty/Property[]/Fee/ProrateType
/PhysicalProperty/Property[]/Fee/LateType
/PhysicalProperty/Property[]/Fee/LatePercent
/PhysicalProperty/Property[]/Fee/LateMinFee
/PhysicalProperty/Property[]/Fee/LateFeePerDay
/PhysicalProperty/Property[]/Fee/NonRefundableHoldFee
/PhysicalProperty/Property[]/Fee/AdminFee
/PhysicalProperty/Property[]/Fee/ApplicationFee