/PhysicalProperty
/PhysicalProperty/Management
/PhysicalProperty/Management/Name
/PhysicalProperty/Management/Address
/PhysicalProperty/Management/Address/Address1
/PhysicalProperty/Management/Address/City
/PhysicalProperty/Management/Address/State
/PhysicalProperty/Management/Address/Zip
/PhysicalProperty/Management/Address/Country
/PhysicalProperty/Management/Phone
/PhysicalProperty/Management/Phone/Number
/PhysicalProperty/Management/Phone/Description
/PhysicalProperty/Management/Fax
/PhysicalProperty/Management/Fax/Number
/PhysicalProperty/Management/Fax/Description
/PhysicalProperty/Management/Contact
/PhysicalProperty/Management/Contact/Name
/PhysicalProperty/Management/Contact/Phone
/PhysicalProperty/Management/Contact/Phone/Number
/PhysicalProperty/Management/Contact/Phone/Description
/PhysicalProperty/Management/Contact/Fax
/PhysicalProperty/Management/Contact/Fax/Number
/PhysicalProperty/Management/Contact/Fax/Description
/PhysicalProperty/Management/Contact/Email
/PhysicalProperty/Management/Contact/Description
/PhysicalProperty/Property[]
/PhysicalProperty/Property[]/Identification
/PhysicalProperty/Property[]/Identification/PrimaryID
/PhysicalProperty/Property[]/Identification/SecondaryID
/PhysicalProperty/Property[]/Identification/General_ID[]
/PhysicalProperty/Property[]/Identification/General_ID[]/ID
/PhysicalProperty/Property[]/Identification/General_ID[]/Description
/PhysicalProperty/Property[]/Identification/MarketingName
/PhysicalProperty/Property[]/Identification/OwnerLegalName
/PhysicalProperty/Property[]/Identification/Address
/PhysicalProperty/Property[]/Identification/Address/Address1
/PhysicalProperty/Property[]/Identification/Address/City
/PhysicalProperty/Property[]/Identification/Address/State
/PhysicalProperty/Property[]/Identification/Address/Zip
/PhysicalProperty/Property[]/Identification/Address/Country
/PhysicalProperty/Property[]/Identification/Address/PO_Box
/PhysicalProperty/Property[]/Identification/Address/MailingAddress
/PhysicalProperty/Property[]/Identification/Address/ShippingAddress
/PhysicalProperty/Property[]/Identification/Latitude
/PhysicalProperty/Property[]/Identification/Longitude
/PhysicalProperty/Property[]/Identification/Phone
/PhysicalProperty/Property[]/Identification/Phone/Number
/PhysicalProperty/Property[]/Identification/Phone/Description
/PhysicalProperty/Property[]/Identification/Fax
/PhysicalProperty/Property[]/Identification/Fax/Number
/PhysicalProperty/Property[]/Identification/Fax/Description
/PhysicalProperty/Property[]/Identification/Email
/PhysicalProperty/Property[]/Identification/LastUpdate
/PhysicalProperty/Property[]/Information
/PhysicalProperty/Property[]/Information/StructureType
/PhysicalProperty/Property[]/Information/BuildingCount
/PhysicalProperty/Property[]/Information/UnitCount
/PhysicalProperty/Property[]/Information/LongDescription
/PhysicalProperty/Property[]/Information/DrivingDirections
/PhysicalProperty/Property[]/Information/LeaseLength
/PhysicalProperty/Property[]/OnSiteContact
/PhysicalProperty/Property[]/OnSiteContact/FirstName
/PhysicalProperty/Property[]/OnSiteContact/LastName
/PhysicalProperty/Property[]/OnSiteContact/Title
/PhysicalProperty/Property[]/OnSiteContact/Email
/PhysicalProperty/Property[]/OnSiteContact/Phone
/PhysicalProperty/Property[]/OnSiteContact/Phone/Number
/PhysicalProperty/Property[]/OnSiteContact/Phone/Description
/PhysicalProperty/Property[]/OnSiteContact/Fax
/PhysicalProperty/Property[]/OnSiteContact/Fax/Number
/PhysicalProperty/Property[]/OnSiteContact/Fax/Description
/PhysicalProperty/Property[]/Fee
/PhysicalProperty/Property[]/Fee/ProrateType
/PhysicalProperty/Property[]/Fee/LateType
/PhysicalProperty/Property[]/Fee/LatePercent
/PhysicalProperty/Property[]/Fee/LateMinFee
/PhysicalProperty/Property[]/Fee/LateFeePerDay
/PhysicalProperty/Property[]/Fee/NonRefundableHoldFee
/PhysicalProperty/Property[]/Fee/AdminFee
/PhysicalProperty/Property[]/Fee/ApplicationFee
/PhysicalProperty/Property[]/Policy
/PhysicalProperty/Property[]/Policy/Pet
/PhysicalProperty/Property[]/Policy/Pet/Comment
/PhysicalProperty/Property[]/Building
/PhysicalProperty/Property[]/Building/Name
/PhysicalProperty/Property[]/Building/Description
/PhysicalProperty/Property[]/Building/UnitCount
/PhysicalProperty/Property[]/Building/SquareFeet
/PhysicalProperty/Property[]/Floorplan[]
/PhysicalProperty/Property[]/Floorplan[]/Name
/PhysicalProperty/Property[]/Floorplan[]/Comment
/PhysicalProperty/Property[]/Floorplan[]/UnitCount
/PhysicalProperty/Property[]/Floorplan[]/Room[]
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Count
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Comment
/PhysicalProperty/Property[]/Floorplan[]/SquareFeet
/PhysicalProperty/Property[]/Floorplan[]/MarketRent
/PhysicalProperty/Property[]/Floorplan[]/EffectiveRent
/PhysicalProperty/Property[]/Floorplan[]/Deposit
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Amount
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Description
/PhysicalProperty/Property[]/Floorplan[]/Deposit/PercentRefundable
/PhysicalProperty/Property[]/Floorplan[]/Deposit/PortionRefundable
/PhysicalProperty/Property[]/Floorplan[]/Amenities
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Balcony
/PhysicalProperty/Property[]/Floorplan[]/Amenities/CeilingFan
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Fireplace
/PhysicalProperty/Property[]/Floorplan[]/Amenities/LargeClosets
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Patio
/PhysicalProperty/Property[]/Floorplan[]/Amenities/PrivateBalcony
/PhysicalProperty/Property[]/Floorplan[]/Amenities/PrivatePatio
/PhysicalProperty/Property[]/Floorplan[]/Amenities/WD_Hookup
/PhysicalProperty/Property[]/Floorplan[]/Amenities/WindowCoverings
/PhysicalProperty/Property[]/Floorplan[]/Amenities/CustomAmenity
/PhysicalProperty/Property[]/Floorplan[]/Fee
/PhysicalProperty/Property[]/Floorplan[]/Fee/ProrateType
/PhysicalProperty/Property[]/Floorplan[]/Fee/LateType
/PhysicalProperty/Property[]/Floorplan[]/Fee/LatePercent
/PhysicalProperty/Property[]/Floorplan[]/Fee/LateMinFee
/PhysicalProperty/Property[]/Floorplan[]/Fee/LateFeePerDay
/PhysicalProperty/Property[]/Floorplan[]/Fee/NonRefundableHoldFee
/PhysicalProperty/Property[]/Floorplan[]/Fee/AdminFee
/PhysicalProperty/Property[]/Floorplan[]/Fee/ApplicationFee
/PhysicalProperty/Property[]/Amenities
/PhysicalProperty/Property[]/Amenities/Community
/PhysicalProperty/Property[]/Amenities/Community/DoorAttendant
/PhysicalProperty/Property[]/Amenities/Community/HighSpeed
/PhysicalProperty/Property[]/Amenities/Community/Pool
/PhysicalProperty/Property[]/Amenities/Floorplan
/PhysicalProperty/Property[]/Promotional[]
/PhysicalProperty/Property[]/Identification/General_ID
/PhysicalProperty/Property[]/Identification/General_ID/ID
/PhysicalProperty/Property[]/Identification/General_ID/Description
/PhysicalProperty/Property[]/Identification/MSA_Number
/PhysicalProperty/Property[]/Identification/County
/PhysicalProperty/Property[]/Amenities/Community/BasketballCourt
/PhysicalProperty/Property[]/Amenities/Community/CoverPark
/PhysicalProperty/Property[]/Amenities/Community/FitnessCenter
/PhysicalProperty/Property[]/Amenities/Community/Laundry
/PhysicalProperty/Property[]/Amenities/Community/VolleyballCourt
/PhysicalProperty/Property[]/Amenities/Community/CustomAmenity
/PhysicalProperty/Property[]/Identification/Phone[]
/PhysicalProperty/Property[]/Identification/Phone[]/Number
/PhysicalProperty/Property[]/Identification/Phone[]/Description
/PhysicalProperty/Property[]/Amenities/Community/Concierge
/PhysicalProperty/Property[]/Amenities/Community/OnSiteMaintenance
/PhysicalProperty/Property[]/Amenities/Community/PlayGround
/PhysicalProperty/Property[]/Floorplan[]/Amenities/DishWasher
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Disposal
/PhysicalProperty/Property[]/Amenities/Community/BusinessCenter
/PhysicalProperty/Property[]/Amenities/Community/RecRoom
/PhysicalProperty/Property[]/Building[]
/PhysicalProperty/Property[]/Building[]/Name
/PhysicalProperty/Property[]/Building[]/Description
/PhysicalProperty/Property[]/Building[]/UnitCount
/PhysicalProperty/Property[]/Building[]/SquareFeet
/PhysicalProperty/Property[]/Amenities/Community/ClubHouse
/PhysicalProperty/Property[]/Amenities/Community/Sauna
/PhysicalProperty/Property[]/Floorplan[]/Concession
/PhysicalProperty/Property[]/Floorplan[]/Concession/Value
/PhysicalProperty/Property[]/Floorplan[]/Concession/Term
/PhysicalProperty/Property[]/Floorplan[]/Concession/Description
/PhysicalProperty/Property[]/Amenities/Community/ShortTermLease
/PhysicalProperty/Property[]/Amenities/Community/TVLounge
/PhysicalProperty/Property[]/Floorplan[]/Amenities/WheelChair
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Garage
/PhysicalProperty/Property[]/Floorplan[]/Amenities/ControlledAccess
/PhysicalProperty/Property[]/Floorplan[]/Amenities/AdditionalStorage
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Microwave
/PhysicalProperty/Property[]/Amenities/Community/Elevator
/PhysicalProperty/Property[]/Amenities/Community/Garage
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Alarm
/PhysicalProperty/Property[]/Floorplan[]/Amenities/Furnished
/PhysicalProperty/Property[]/Amenities/Community/Gate
/PhysicalProperty/Property[]/Amenities/Community/StorageSpace
/PhysicalProperty/Property[]/Identification/Address/Address2
/PhysicalProperty/Property[]/Concession
/PhysicalProperty/Property[]/Concession/Value
/PhysicalProperty/Property[]/Concession/Term
/PhysicalProperty/Property[]/Concession/Description
/PhysicalProperty/Property[]/Floorplan[]/Amenities/View