/PhysicalProperty
/PhysicalProperty/Management
/PhysicalProperty/Management/Name
/PhysicalProperty/Management/Logo
/PhysicalProperty/Management/WebSite
/PhysicalProperty/Property[]
/PhysicalProperty/Property[]/Identification
/PhysicalProperty/Property[]/Identification/PrimaryID
/PhysicalProperty/Property[]/Identification/SecondaryID
/PhysicalProperty/Property[]/Identification/General_ID
/PhysicalProperty/Property[]/Identification/General_ID/ID
/PhysicalProperty/Property[]/Identification/General_ID/Description
/PhysicalProperty/Property[]/Identification/MarketingName
/PhysicalProperty/Property[]/Identification/OwnerLegalName
/PhysicalProperty/Property[]/Identification/Address
/PhysicalProperty/Property[]/Identification/Address/Address1
/PhysicalProperty/Property[]/Identification/Address/City
/PhysicalProperty/Property[]/Identification/Address/State
/PhysicalProperty/Property[]/Identification/Address/Zip
/PhysicalProperty/Property[]/Identification/Address/Country
/PhysicalProperty/Property[]/Identification/Address/PO_Box
/PhysicalProperty/Property[]/Identification/Address/MailingAddress
/PhysicalProperty/Property[]/Identification/Address/ShippingAddress
/PhysicalProperty/Property[]/Identification/MSA_Name
/PhysicalProperty/Property[]/Identification/Latitude
/PhysicalProperty/Property[]/Identification/Longitude
/PhysicalProperty/Property[]/Identification/WebSite
/PhysicalProperty/Property[]/Identification/Phone
/PhysicalProperty/Property[]/Identification/Phone/Number
/PhysicalProperty/Property[]/Identification/Email
/PhysicalProperty/Property[]/Information
/PhysicalProperty/Property[]/Information/StructureType
/PhysicalProperty/Property[]/Information/UnitCount
/PhysicalProperty/Property[]/Information/YearBuilt
/PhysicalProperty/Property[]/Information/StartRent
/PhysicalProperty/Property[]/Information/OfficeHour[]
/PhysicalProperty/Property[]/Information/OfficeHour[]/OpenTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/CloseTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/Day
/PhysicalProperty/Property[]/Information/ShortDescription
/PhysicalProperty/Property[]/Information/LongDescription
/PhysicalProperty/Property[]/Information/DrivingDirections
/PhysicalProperty/Property[]/Information/LeaseLength
/PhysicalProperty/Property[]/Information/Parking[]
/PhysicalProperty/Property[]/Information/Parking[]/Assigned
/PhysicalProperty/Property[]/Information/Parking[]/SpaceFee
/PhysicalProperty/Property[]/Information/Parking[]/Spaces
/PhysicalProperty/Property[]/Information/Parking[]/Comment
/PhysicalProperty/Property[]/Accounting
/PhysicalProperty/Property[]/Accounting/LiveDate
/PhysicalProperty/Property[]/Accounting/LiveFlag
/PhysicalProperty/Property[]/Accounting/LastDayBegin
/PhysicalProperty/Property[]/Accounting/LastDayEnd
/PhysicalProperty/Property[]/Accounting/LastAccMthEnd
/PhysicalProperty/Property[]/Accounting/AcctMthEndFlag
/PhysicalProperty/Property[]/Accounting/LastInvoiceNumber
/PhysicalProperty/Property[]/Accounting/LastReceiptNumber
/PhysicalProperty/Property[]/Accounting/CashReserve
/PhysicalProperty/Property[]/Accounting/EndOfYear
/PhysicalProperty/Property[]/Accounting/AccountsReceivable
/PhysicalProperty/Property[]/Accounting/AccountsPayable
/PhysicalProperty/Property[]/Accounting/GeneralLedger
/PhysicalProperty/Property[]/Accounting/CurrentAccountingPeriod
/PhysicalProperty/Property[]/Accounting/CurrentAccountingPeriodAR
/PhysicalProperty/Property[]/Accounting/CurrentAccountingPeriodAP
/PhysicalProperty/Property[]/Accounting/TaxCredit
/PhysicalProperty/Property[]/Payment
/PhysicalProperty/Property[]/Payment/RemitTo
/PhysicalProperty/Property[]/Payment/RemitTo/Address1
/PhysicalProperty/Property[]/Payment/RemitTo/Address2
/PhysicalProperty/Property[]/Payment/RemitTo/City
/PhysicalProperty/Property[]/Payment/RemitTo/State
/PhysicalProperty/Property[]/Payment/RemitTo/Province
/PhysicalProperty/Property[]/Payment/RemitTo/Zip
/PhysicalProperty/Property[]/Payment/RemitTo/Country
/PhysicalProperty/Property[]/Payment/CheckPayable
/PhysicalProperty/Property[]/Policy
/PhysicalProperty/Property[]/Policy/Pet[]
/PhysicalProperty/Property[]/Policy/Pet[]/Comment
/PhysicalProperty/Property[]/Policy/Pet[]/MaxCount
/PhysicalProperty/Property[]/Policy/Pet[]/Deposit
/PhysicalProperty/Property[]/Policy/Pet[]/Rent
/PhysicalProperty/Property[]/Policy/Pet[]/Weight
/PhysicalProperty/Property[]/Policy/Pet[]/Restrictions
/PhysicalProperty/Property[]/Floorplan[]
/PhysicalProperty/Property[]/Floorplan[]/Name
/PhysicalProperty/Property[]/Floorplan[]/UnitCount
/PhysicalProperty/Property[]/Floorplan[]/UnitsAvailable
/PhysicalProperty/Property[]/Floorplan[]/Room[]
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Count
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Comment
/PhysicalProperty/Property[]/Floorplan[]/SquareFeet
/PhysicalProperty/Property[]/Floorplan[]/MarketRent
/PhysicalProperty/Property[]/Floorplan[]/EffectiveRent
/PhysicalProperty/Property[]/Floorplan[]/Deposit
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Amount
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Description
/PhysicalProperty/Property[]/Floorplan[]/Deposit/PercentRefundable
/PhysicalProperty/Property[]/Floorplan[]/Deposit/PortionRefundable
/PhysicalProperty/Property[]/Floorplan[]/Fee
/PhysicalProperty/Property[]/Floorplan[]/Fee/ProrateType
/PhysicalProperty/Property[]/Floorplan[]/Fee/LateType
/PhysicalProperty/Property[]/Floorplan[]/Fee/LatePercent
/PhysicalProperty/Property[]/Floorplan[]/Fee/LateMinFee
/PhysicalProperty/Property[]/Floorplan[]/Fee/LateFeePerDay
/PhysicalProperty/Property[]/Floorplan[]/Fee/NonRefundableHoldFee
/PhysicalProperty/Property[]/Floorplan[]/Fee/AdminFee
/PhysicalProperty/Property[]/Floorplan[]/Fee/ApplicationFee
/PhysicalProperty/Property[]/Floorplan[]/Amenities
/PhysicalProperty/Property[]/Floorplan[]/Amenities/General
/PhysicalProperty/Property[]/Amenities
/PhysicalProperty/Property[]/Amenities/Community
/PhysicalProperty/Property[]/Amenities/Community/BasketballCourt
/PhysicalProperty/Property[]/Amenities/Community/BusinessCenter
/PhysicalProperty/Property[]/Amenities/Community/ClubHouse
/PhysicalProperty/Property[]/Amenities/Community/Concierge
/PhysicalProperty/Property[]/Amenities/Community/CoverPark
/PhysicalProperty/Property[]/Amenities/Community/FitnessCenter
/PhysicalProperty/Property[]/Amenities/Community/Elevator
/PhysicalProperty/Property[]/Amenities/Community/Garage
/PhysicalProperty/Property[]/Amenities/Community/Gate
/PhysicalProperty/Property[]/Amenities/Community/HighSpeed
/PhysicalProperty/Property[]/Amenities/Community/Housekeeping
/PhysicalProperty/Property[]/Amenities/Community/Laundry
/PhysicalProperty/Property[]/Amenities/Community/Pool
/PhysicalProperty/Property[]/Amenities/Community/PlayGround
/PhysicalProperty/Property[]/Amenities/Community/Racquetball
/PhysicalProperty/Property[]/Amenities/Community/Sauna
/PhysicalProperty/Property[]/Amenities/Community/ShortTermLease
/PhysicalProperty/Property[]/Amenities/Community/Spa
/PhysicalProperty/Property[]/Amenities/Community/StorageSpace
/PhysicalProperty/Property[]/Amenities/Community/TennisCourt
/PhysicalProperty/Property[]/Amenities/Community/Transportation
/PhysicalProperty/Property[]/Amenities/Community/VolleyballCourt
/PhysicalProperty/Property[]/Amenities/Floorplan
/PhysicalProperty/Property[]/Amenities/Floorplan/AdditionalStorage
/PhysicalProperty/Property[]/Amenities/Floorplan/AirConditioner
/PhysicalProperty/Property[]/Amenities/Floorplan/Alarm
/PhysicalProperty/Property[]/Amenities/Floorplan/Balcony
/PhysicalProperty/Property[]/Amenities/Floorplan/CableSat
/PhysicalProperty/Property[]/Amenities/Floorplan/Carport
/PhysicalProperty/Property[]/Amenities/Floorplan/CeilingFan
/PhysicalProperty/Property[]/Amenities/Floorplan/ControlledAccess
/PhysicalProperty/Property[]/Amenities/Floorplan/Courtyard
/PhysicalProperty/Property[]/Amenities/Floorplan/DishWasher
/PhysicalProperty/Property[]/Amenities/Floorplan/Disposal
/PhysicalProperty/Property[]/Amenities/Floorplan/Dryer
/PhysicalProperty/Property[]/Amenities/Floorplan/Fireplace
/PhysicalProperty/Property[]/Amenities/Floorplan/Furnished
/PhysicalProperty/Property[]/Amenities/Floorplan/Garage
/PhysicalProperty/Property[]/Amenities/Floorplan/Handrails
/PhysicalProperty/Property[]/Amenities/Floorplan/IndividualClimateControl
/PhysicalProperty/Property[]/Amenities/Floorplan/LargeClosets
/PhysicalProperty/Property[]/Amenities/Floorplan/Microwave
/PhysicalProperty/Property[]/Amenities/Floorplan/Patio
/PhysicalProperty/Property[]/Amenities/Floorplan/PrivateBalcony
/PhysicalProperty/Property[]/Amenities/Floorplan/PrivatePatio
/PhysicalProperty/Property[]/Amenities/Floorplan/Refrigerator
/PhysicalProperty/Property[]/Amenities/Floorplan/Skylight
/PhysicalProperty/Property[]/Amenities/Floorplan/View
/PhysicalProperty/Property[]/Amenities/Floorplan/Washer
/PhysicalProperty/Property[]/Amenities/Floorplan/WheelChair
/PhysicalProperty/Property[]/Amenities/Floorplan/WD_Hookup
/PhysicalProperty/Property[]/Amenities/Floorplan/WindowCoverings
/PhysicalProperty/Property[]/Amenities/General[]
/PhysicalProperty/Property[]/Amenities/General[]/AmenityName
/PhysicalProperty/Property[]/Amenities/General[]/AmenityCharge
/PhysicalProperty/Property[]/Amenities/General[]/AmenityRank
/PhysicalProperty/Property[]/Amenities/General[]/AdditionalAmenity
/PhysicalProperty/Property[]/File[]
/PhysicalProperty/Property[]/File[]/Type
/PhysicalProperty/Property[]/File[]/Name
/PhysicalProperty/Property[]/File[]/Caption
/PhysicalProperty/Property[]/File[]/Format
/PhysicalProperty/Property[]/File[]/Src
/PhysicalProperty/Property[]/File[]/Width
/PhysicalProperty/Property[]/File[]/Height
/PhysicalProperty/Property[]/File[]/Rank
/PhysicalProperty/Property[]/Promotional
/PhysicalProperty/Property[]/Information/Parking
/PhysicalProperty/Property[]/Information/Parking/Assigned
/PhysicalProperty/Property[]/Information/Parking/SpaceFee
/PhysicalProperty/Property[]/Information/Parking/Spaces
/PhysicalProperty/Property[]/Information/Parking/Comment
/PhysicalProperty/Property[]/Policy/Pet[]/Fee
/PhysicalProperty/Property[]/Floorplan
/PhysicalProperty/Property[]/Floorplan/Name
/PhysicalProperty/Property[]/Floorplan/UnitCount
/PhysicalProperty/Property[]/Floorplan/UnitsAvailable
/PhysicalProperty/Property[]/Floorplan/Room[]
/PhysicalProperty/Property[]/Floorplan/Room[]/Count
/PhysicalProperty/Property[]/Floorplan/Room[]/Comment
/PhysicalProperty/Property[]/Floorplan/SquareFeet
/PhysicalProperty/Property[]/Floorplan/MarketRent
/PhysicalProperty/Property[]/Floorplan/EffectiveRent
/PhysicalProperty/Property[]/Floorplan/Deposit
/PhysicalProperty/Property[]/Floorplan/Deposit/Amount
/PhysicalProperty/Property[]/Floorplan/Deposit/Description
/PhysicalProperty/Property[]/Floorplan/Deposit/PercentRefundable
/PhysicalProperty/Property[]/Floorplan/Deposit/PortionRefundable
/PhysicalProperty/Property[]/Floorplan/Fee
/PhysicalProperty/Property[]/Floorplan/Fee/ProrateType
/PhysicalProperty/Property[]/Floorplan/Fee/LateType
/PhysicalProperty/Property[]/Floorplan/Fee/LatePercent
/PhysicalProperty/Property[]/Floorplan/Fee/LateMinFee
/PhysicalProperty/Property[]/Floorplan/Fee/LateFeePerDay
/PhysicalProperty/Property[]/Floorplan/Fee/NonRefundableHoldFee
/PhysicalProperty/Property[]/Floorplan/Fee/AdminFee
/PhysicalProperty/Property[]/Floorplan/Fee/ApplicationFee
/PhysicalProperty/Property[]/Floorplan/Amenities
/PhysicalProperty/Property[]/Floorplan/Amenities/General
/PhysicalProperty/Property[]/File
/PhysicalProperty/Property[]/File/Type
/PhysicalProperty/Property[]/File/Name
/PhysicalProperty/Property[]/File/Caption
/PhysicalProperty/Property[]/File/Format
/PhysicalProperty/Property[]/File/Src
/PhysicalProperty/Property[]/File/Width
/PhysicalProperty/Property[]/File/Height
/PhysicalProperty/Property[]/File/Rank