/PhysicalProperty
/PhysicalProperty/Property[]
/PhysicalProperty/Property[]/Identification
/PhysicalProperty/Property[]/Identification/PrimaryID
/PhysicalProperty/Property[]/Identification/MarketingName
/PhysicalProperty/Property[]/Identification/OwnerLegalName
/PhysicalProperty/Property[]/Identification/Address
/PhysicalProperty/Property[]/Identification/Address/Address1
/PhysicalProperty/Property[]/Identification/Address/City
/PhysicalProperty/Property[]/Identification/Address/State
/PhysicalProperty/Property[]/Identification/Address/Zip
/PhysicalProperty/Property[]/Identification/Address/Country
/PhysicalProperty/Property[]/Identification/Address/PO_Box
/PhysicalProperty/Property[]/Identification/Address/MailingAddress
/PhysicalProperty/Property[]/Identification/Address/ShippingAddress
/PhysicalProperty/Property[]/Identification/Latitude
/PhysicalProperty/Property[]/Identification/Longitude
/PhysicalProperty/Property[]/Identification/Fax
/PhysicalProperty/Property[]/Identification/Fax/Number
/PhysicalProperty/Property[]/Identification/Website
/PhysicalProperty/Property[]/Information
/PhysicalProperty/Property[]/Information/StructureType
/PhysicalProperty/Property[]/Information/UnitCount
/PhysicalProperty/Property[]/Information/OfficeHour[]
/PhysicalProperty/Property[]/Information/OfficeHour[]/OpenTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/CloseTime
/PhysicalProperty/Property[]/Information/OfficeHour[]/Day
/PhysicalProperty/Property[]/Information/LongDescription
/PhysicalProperty/Property[]/Information/LeaseLength
/PhysicalProperty/Property[]/Information/DrivingDirections
/PhysicalProperty/Property[]/Promotional
/PhysicalProperty/Property[]/OnSiteContact
/PhysicalProperty/Property[]/OnSiteContact/FirstName
/PhysicalProperty/Property[]/OnSiteContact/LastName
/PhysicalProperty/Property[]/OnSiteContact/Title
/PhysicalProperty/Property[]/OnSiteContact/Email
/PhysicalProperty/Property[]/OnSiteContact/Phone
/PhysicalProperty/Property[]/OnSiteContact/Phone/Number
/PhysicalProperty/Property[]/OnSiteContact/Phone/Description
/PhysicalProperty/Property[]/Policy
/PhysicalProperty/Property[]/Policy/Pet[]
/PhysicalProperty/Property[]/Policy/Pet[]/Comment
/PhysicalProperty/Property[]/Policy/Pet[]/MaxCount
/PhysicalProperty/Property[]/Policy/Pet[]/Deposit
/PhysicalProperty/Property[]/Policy/Pet[]/Fee
/PhysicalProperty/Property[]/Policy/Pet[]/Rent
/PhysicalProperty/Property[]/Policy/Pet[]/Weight
/PhysicalProperty/Property[]/Policy/Pet[]/FeeRange
/PhysicalProperty/Property[]/Policy/Pet[]/Restrictions
/PhysicalProperty/Property[]/Policy/Pet[]/PetCare
/PhysicalProperty/Property[]/Floorplan[]
/PhysicalProperty/Property[]/Floorplan[]/Name
/PhysicalProperty/Property[]/Floorplan[]/Comment
/PhysicalProperty/Property[]/Floorplan[]/UnitCount
/PhysicalProperty/Property[]/Floorplan[]/Room[]
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Count
/PhysicalProperty/Property[]/Floorplan[]/Room[]/Comment
/PhysicalProperty/Property[]/Floorplan[]/SquareFeet
/PhysicalProperty/Property[]/Floorplan[]/MarketRent
/PhysicalProperty/Property[]/Floorplan[]/EffectiveRent
/PhysicalProperty/Property[]/Floorplan[]/Deposit
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Amount
/PhysicalProperty/Property[]/Floorplan[]/Deposit/Description
/PhysicalProperty/Property[]/Floorplan[]/Deposit/PercentRefundable
/PhysicalProperty/Property[]/Floorplan[]/Deposit/PortionRefundable
/PhysicalProperty/Property[]/Floorplan[]/Amenities
/PhysicalProperty/Property[]/Floorplan[]/Amenities/General
/PhysicalProperty/Property[]/Amenities
/PhysicalProperty/Property[]/Amenities/Community
/PhysicalProperty/Property[]/Amenities/Community/General[]
/PhysicalProperty/Property[]/Amenities/Community/General[]/AmenityName
/PhysicalProperty/Property[]/Amenities/Community/General[]/AmenityCharge
/PhysicalProperty/Property[]/Amenities/Community/General[]/AmenityRank
/PhysicalProperty/Property[]/Amenities/Community/General[]/AdditionalAmenity
/PhysicalProperty/Property[]/Amenities/Floorplan
/PhysicalProperty/Property[]/Amenities/Floorplan/General[]
/PhysicalProperty/Property[]/Amenities/Floorplan/General[]/AmenityName
/PhysicalProperty/Property[]/Amenities/Floorplan/General[]/AmenityCharge
/PhysicalProperty/Property[]/Amenities/Floorplan/General[]/AmenityRank
/PhysicalProperty/Property[]/Amenities/Floorplan/General[]/AdditionalAmenity
/PhysicalProperty/Property[]/Utility
/PhysicalProperty/Property[]/Utility/AirCon
/PhysicalProperty/Property[]/Utility/BroadbandInternet
/PhysicalProperty/Property[]/Utility/Cable
/PhysicalProperty/Property[]/Utility/Electric
/PhysicalProperty/Property[]/Utility/Gas
/PhysicalProperty/Property[]/Utility/Heat
/PhysicalProperty/Property[]/Utility/HotWater
/PhysicalProperty/Property[]/Utility/Satellite
/PhysicalProperty/Property[]/Utility/Sewer
/PhysicalProperty/Property[]/Utility/Telephone
/PhysicalProperty/Property[]/Utility/Trash
/PhysicalProperty/Property[]/Utility/Water
/PhysicalProperty/Property[]/Utility/UtilityPortionIncluded
/PhysicalProperty/Property[]/File[]
/PhysicalProperty/Property[]/File[]/Type
/PhysicalProperty/Property[]/File[]/Name
/PhysicalProperty/Property[]/File[]/Caption
/PhysicalProperty/Property[]/File[]/Format
/PhysicalProperty/Property[]/File[]/Src
/PhysicalProperty/Property[]/File[]/Width
/PhysicalProperty/Property[]/File[]/Height
/PhysicalProperty/Property[]/File[]/Rank
/PhysicalProperty/Property[]/Identification/Phone
/PhysicalProperty/Property[]/Identification/Phone/Number
/PhysicalProperty/Property[]/Identification/Phone/Description
/PhysicalProperty/Property[]/Amenities/Community/Available24Hours
/PhysicalProperty/Property[]/Amenities/Community/BasketballCourt
/PhysicalProperty/Property[]/Amenities/Community/BusinessCenter
/PhysicalProperty/Property[]/Amenities/Community/ChildCare
/PhysicalProperty/Property[]/Amenities/Community/ClubDiscount
/PhysicalProperty/Property[]/Amenities/Community/ClubHouse
/PhysicalProperty/Property[]/Amenities/Community/Concierge
/PhysicalProperty/Property[]/Amenities/Community/CoverPark
/PhysicalProperty/Property[]/Amenities/Community/DoorAttendant
/PhysicalProperty/Property[]/Amenities/Community/FitnessCenter
/PhysicalProperty/Property[]/Amenities/Community/Elevator
/PhysicalProperty/Property[]/Amenities/Community/FreeWeights
/PhysicalProperty/Property[]/Amenities/Community/Garage
/PhysicalProperty/Property[]/Amenities/Community/Gate
/PhysicalProperty/Property[]/Amenities/Community/GroupExcercise
/PhysicalProperty/Property[]/Amenities/Community/GuestRoom
/PhysicalProperty/Property[]/Amenities/Community/HighSpeed
/PhysicalProperty/Property[]/Amenities/Community/Housekeeping
/PhysicalProperty/Property[]/Amenities/Community/HouseSitting
/PhysicalProperty/Property[]/Amenities/Community/Laundry
/PhysicalProperty/Property[]/Amenities/Community/Library
/PhysicalProperty/Property[]/Amenities/Community/MealService
/PhysicalProperty/Property[]/Amenities/Community/NightPatrol
/PhysicalProperty/Property[]/Amenities/Community/OnSiteMaintenance
/PhysicalProperty/Property[]/Amenities/Community/OnSiteManagement
/PhysicalProperty/Property[]/Amenities/Community/PackageReceiving
/PhysicalProperty/Property[]/Amenities/Community/Pool
/PhysicalProperty/Property[]/Amenities/Community/PlayGround
/PhysicalProperty/Property[]/Amenities/Community/Racquetball
/PhysicalProperty/Property[]/Amenities/Community/RecRoom
/PhysicalProperty/Property[]/Amenities/Community/Sauna
/PhysicalProperty/Property[]/Amenities/Community/ShortTermLease
/PhysicalProperty/Property[]/Amenities/Community/Spa
/PhysicalProperty/Property[]/Amenities/Community/StorageSpace
/PhysicalProperty/Property[]/Amenities/Community/Sundeck
/PhysicalProperty/Property[]/Amenities/Community/TennisCourt
/PhysicalProperty/Property[]/Amenities/Community/Transportation
/PhysicalProperty/Property[]/Amenities/Community/TVLounge
/PhysicalProperty/Property[]/Amenities/Community/Vintage
/PhysicalProperty/Property[]/Amenities/Community/VolleyballCourt
/PhysicalProperty/Property[]/Amenities/Floorplan/AdditionalStorage
/PhysicalProperty/Property[]/Amenities/Floorplan/AirConditioner
/PhysicalProperty/Property[]/Amenities/Floorplan/Alarm
/PhysicalProperty/Property[]/Amenities/Floorplan/Balcony
/PhysicalProperty/Property[]/Amenities/Floorplan/Cable
/PhysicalProperty/Property[]/Amenities/Floorplan/Carport
/PhysicalProperty/Property[]/Amenities/Floorplan/CeilingFan
/PhysicalProperty/Property[]/Amenities/Floorplan/ControlledAccess
/PhysicalProperty/Property[]/Amenities/Floorplan/Courtyard
/PhysicalProperty/Property[]/Amenities/Floorplan/DishWasher
/PhysicalProperty/Property[]/Amenities/Floorplan/Disposal
/PhysicalProperty/Property[]/Amenities/Floorplan/Dryer
/PhysicalProperty/Property[]/Amenities/Floorplan/Fireplace
/PhysicalProperty/Property[]/Amenities/Floorplan/Furnished
/PhysicalProperty/Property[]/Amenities/Floorplan/Garage
/PhysicalProperty/Property[]/Amenities/Floorplan/Handrails
/PhysicalProperty/Property[]/Amenities/Floorplan/IndividualClimateControl
/PhysicalProperty/Property[]/Amenities/Floorplan/LargeClosets
/PhysicalProperty/Property[]/Amenities/Floorplan/Microwave
/PhysicalProperty/Property[]/Amenities/Floorplan/Patio
/PhysicalProperty/Property[]/Amenities/Floorplan/PrivateBalcony
/PhysicalProperty/Property[]/Amenities/Floorplan/PrivatePatio
/PhysicalProperty/Property[]/Amenities/Floorplan/Refrigerator
/PhysicalProperty/Property[]/Amenities/Floorplan/Skylight
/PhysicalProperty/Property[]/Amenities/Floorplan/View
/PhysicalProperty/Property[]/Amenities/Floorplan/Washer
/PhysicalProperty/Property[]/Amenities/Floorplan/WheelChair
/PhysicalProperty/Property[]/Amenities/Floorplan/WD_Hookup
/PhysicalProperty/Property[]/Amenities/Floorplan/WindowCoverings